name: 刷步数

on:
  #push:1
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '45 2 * * *' # 修改你的定时配置
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: 开始
        run: |
          pip3 install requests
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}' 
          open_get_weather='${{ secrets.OPEN_GET_WEATHER }}'
          area='${{ secrets.AREA }}'
          sckey='${{ secrets.SCKEY }}'
          python3 main.py ${user} ${passwd} ${open_get_weather} ${area} ${sckey}

      - name: Update Time
        run: |
          time=$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')
          sed -i "s/最后一次运行/最后一次运行时间: $time（北京时间）/g" README.md
        
